### ISSUE TITLE
How to use gnuplot with SVG terminal?

### ISSUE THREAD

**Issue by wucke13** [hertogp/imagine#13]
Having an all vector based PDF ain't worth anything if the plots are rasterized. Scaling with the pngcairo backend in `gnuplot` isn't fun either. How would one use a pdf or svg terminal with `imagine` and `gnuplot`?

**Comment by hertogp** [comment]
Disclaimer: I'm not a gnuplot expert.

However, using "term svg" in a gnuplot script will produce graphics data on stdout in svg-format.

Adding "available_fmts = ["png", "svg"] to the Gnuplot worker, will then lead to the creation of an
svg image in pd-images, which is included in the document via an img-link.

Pandoc then uses whatever is available to include the svg-image in the intended output format.
In my case, it wanted "rsvg2-convert", for which I had to do "sudo apt-get install librsvg2-bin".

I created a test file, converted it to PDF and attached it here.  Is that what you're looking for?
[gnuplot.pdf](https://github.com/hertogp/imagine/files/3884280/gnuplot.pdf)

The "surface" and "tori" examples were each included twice: once with a png terminal and once with an svg terminal.  The svg-examples indeed look better, especially when zooming in.

**Comment by hertogp** [comment]
Source md-file attached here as well (renamed to gnuplot.md.txt since github seems to not like the .md extension).
[gnuplot.md.txt](https://github.com/hertogp/imagine/files/3884283/gnuplot.md.txt)

Converted via "pandoc --filter ../pandoc_imagine.py  gnuplot.md -o gnuplot.pdf", where the "../pandoc.." is referencing the modified pandoc_imagine.py file in its parent directory.

There is a slew of output formats supported by gnuplot, so I would need to test some of the formats supported by gnuplot, eg. jpeg, gif, epslatex pdfcairo, png, pngcairo, ... etc.. Any suggestions on what would be a good and valid subset?

**Comment by wucke13** [comment]
> I created a test file, converted it to PDF and attached it here. Is that what you're looking for?

Yes, thats beautiful!

> Any suggestions on what would be a good and valid subset?

SVG works nicely for many output formats, so in general SVG would be my preference for a generic pandoc filter. However, when I generated a SVG from plantuml, I had serious performance issues when zooming in with multiple PDF readers. EPS worked very well there, so EPS and PDF seems to be the best choice for embedding vector graphics into something which uses LaTeX to generate PDF. It also may be possible that someone wants to use GIF with gnuplot to do animated graphics.

So: `.svg`, `.eps`, `.ps`, `.pdf`, `.gif` would be nice, actually for everything which can generate them (like, plantuml supports `.eps` & `.svg`, so add them for it too please).

**Comment by hertogp** [comment]
The sample.md needs to be split up into 1 file per graphic utility, and I need to install all of them again to check for svg support and test.  I could do a quick new release with gnuplot updated, any other tools you use?

**Comment by wucke13** [comment]
Yes, `plantuml`.  Thank you for the fast support :+1:

**Comment by hertogp** [comment]
ok, updated pandoc_imagine.py, reworked the examples and updated the documentation.  Updating pypi requires more work, since my .pypirc was on a now deceased  machine.  Anyway, you could try
the git version and check the documentation. Limitations on im_fmt are now removed, so you should be able to use both plantuml, gnuplot and other icm svg.

**Comment by hertogp** [comment]
Fixed in 0.1.6
