### ISSUE TITLE
Ability to add custom graphic renderer's

### ISSUE THREAD

**Issue by jahagirdar** [hertogp/imagine#15]
I am finding myself abusing existing renderers by adding aliases/shell scripts to use my custom graph generators in markdown document.
Is it possible to put in a plugin system// Or if it is there, point me to the documentation of it which will allow extending the project with custom graph generators.

**Comment by hertogp** [comment]
There is no plugin system to extend pandoc-imagine using your own python code.  However, you could easiliy add your own by copying one of the existing handlers/workers.  Otherwise, the `shebang` class is a sort of catch-all class in that it relies on having a command available on the (linux) system and you can feed it input on stdin.  The only tricky part is that the script itself, needs to provide the input to the cli command of your choosing.  The boxes.md has an example:

    ```shebang
    #!/bin/bash
    # I seem to have got myself boxed in!
    cat $0 | boxes -d peek -p h4v1
    ```

That would feed the entire code block (`$0`) to itself (as a bash script), which is why the single line of data is commented out to prevent bash from choking on it and pandoc-imagine makes the entire text shows up in a box using the last line (cat $0 | ...).

Along those lines, you could also say something like:

    ```shebang
    #!/bin/bash
    cat << 'EOF' | boxes -d peek -ph4v1
    Never agree with stupid people,
    they'll drag you down to their level
    and then beat you with experience.
                          -- Mark Twain
    EOF
    ```
which just feeds the heredoc to the `boxes -d ...` cli command.  You could try that and replace
the `boxes -d peek -ph4v1` with your own custom graphic renderer and the `Never agree ...`
with the input for your renderer.

Would that work for you?

**Comment by jahagirdar** [comment]
Thanks, I think It should work.
