### ISSUE TITLE
Feature request: inline images

### ISSUE THREAD

**Issue by pbsds** [hertogp/imagine#16]
When combined with [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref#pandoc-crossref-filter-) it is impossible to create [subfigure grids](https://lierdakil.github.io/pandoc-crossref/#subfigure-grid) due to pandoc-imagine inserting the images in their own separate paragraphs.

Adding an option to replace the fenced code blocks with just an image, or perhaps append the resulting image to the previous paragraph would be helpful. This could be something like `im_out="img:inline"` or `im_append=true`.

<details>
<summary>Here is a testcase, the goal is to have the four graphs side-by-side</summary>

~~~~~~~markdown
<div id="fig:sdf_networks" class="subfigures">
```{.dot width=25% #fig:sdf_networks_a caption="TODO"}
graph {
	graph [nodesep=0.1]
	node [style=filled fillcolor=none margin=0 fontsize=20 shape=none label=""]
	n0 [label="(x, y, z)" ]
	n1 [shape=record label="{}" width=0.35 height=0.36 fillcolor=Gray]
	n2 [shape=trapezium orientation=270    height=1.6  fillcolor=SandyBrown]
	n3 [shape=record label="{}" width=0.35 height=0.36 fillcolor=Moccasin]
	n4 [label="SDF"]
}
```
```{.dot width=25% #fig:sdf_networks_b caption="TODO"}
graph {
    graph [nodesep=0.1]
	node [style=filled fillcolor=none margin=0 fontsize=20 shape=none label=""]
	n0 [shape=none label=" \n\nCode\n\n(x, y, z)" ]
	n1 [shape=none width=0.35 label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="11" bgcolor="LightSkyBlue"><tr><td></td></tr><tr><td></td></tr><tr><td></td></tr><tr><td></td></tr><tr><td bgcolor="gray"></td></tr></table>>]
	n2 [shape=trapezium orientation=270    height=1.6  fillcolor=SandyBrown]
	n3 [shape=record label="{}" width=0.35 height=0.36 fillcolor=Moccasin]
	n4 [label="SDF"]
}
```
```{.dot width=25% #fig:sdf_networks_c caption="TODO"}
graph {
    graph [nodesep=0.1]
	node [style=filled fillcolor=none margin=0 fontsize=20 shape=none label=""]
	n1 [shape=record label="{||||||}" height=2.3 width=0.35 fillcolor=Moccasin]
	n2 [shape=trapezium orientation=270 height=2.3  fillcolor=SandyBrown]
	n3 [shape=record label="{|||}" width=0.35 fillcolor=LightSkyBlue]
	n4 [shape=trapezium orientation=90  height=2.3  fillcolor=SandyBrown]
	n5 [shape=record label="{||||||}" height=2.3 width=0.35 fillcolor=Moccasin]
}
```
```{.dot width=25% #fig:sdf_networks_d caption="TODO"}
graph {
    graph [nodesep=0.1]
	node [style=filled fillcolor=none margin=0 fontsize=20 shape=none label=""]
	n1 [shape=record label="{|||}" width=0.35 fillcolor=yellowgreen]
	n1_[label="⋯" width=0 fontsize=30]
	n2 [shape=record label="{|||}" width=0.35 fillcolor=yellowgreen]
	n2_[label="→" width=0 fontsize=30]
	n3 [shape=record label="{|||}" width=0.35 fillcolor=LightSkyBlue]
	n4 [shape=trapezium orientation=90  height=2.3  fillcolor=SandyBrown]
	n5 [shape=record label="{||||||}" height=2.3 width=0.35 fillcolor=Moccasin]
}
```

TODO
</div>
~~~~~~~

</details>

**Comment by hertogp** [comment]
A pandoc-filter is basically a callback that is called for each element in the AST and must return one of:
- None, to keep the original element
- a pandoc element of the same type (block or inline) which replaces the original
- a list of pandoc elements, which is spliced into the list of the parent object
- an empty list, which deletes the original element

So simply returning an `Image` inline-element as the result of processing a `CodeBlock` block-element (by not wrapping it in a `Para` block-element)  yields an filter error: `Error in $.blocks[0].c[1][0]: mempty` (I tried).

The only way this might work, is to process a `Div` as well.  Since a `Div` is a block-element whose contents is a list of block-elements, it should be possible to process its elements individually and then *merge* contiguous `Para`'s whose contents consists of a single `Image` and return the `Div` with all its attributes intact (maybe stripping an `im_inline` class).

Note that using any `im_out` option (other than "img", which is the default) is likely to mess up the intended result.

I'll give it a go ..

**Comment by hertogp** [comment]
Could you test if `pandoc-imagine` now handles your use-case?  Simply copy [pandoc_imagine.py](https://github.com/hertogp/imagine/blob/master/pandoc_imagine.py) to a temp directory and run e.g.:
```bash
$ pandoc --filter ./pandoc_imagine.py inline.md -o inline.pdf
```
And using inline.md (just rename inline.md.txt to inline.md) should yield inline.pdf.

If that handles your use case, I'll add some more tests and figure out how to do the pypi vodoo dance again to publish a new version.
[inline.pdf](https://github.com/hertogp/imagine/files/5321988/inline.pdf)

[inline.md.txt](https://github.com/hertogp/imagine/files/5321989/inline.md.txt)

**Comment by pbsds** [comment]
Seems to work great! Very nice of you to address my issue this quickly.

I don't seem to have any issues with the ellipsis. Might be platform dependent.

I don't know why the captions per subfigure in your PDF dissapeared, but they work on my end:
![image](https://user-images.githubusercontent.com/140964/94999625-eb9e2d00-05ba-11eb-84d1-6e2b977b539e.png)

Might be because `pandoc-crossref` is picky about being run last.

**Comment by hertogp** [comment]
Probably, since I produced the pdf without `pandoc-crossref'.  Anyway, the ellipses are not a problem for graphviz when processing the codeblock into an image.  It is only my latex-engine that can't handle the ellipses when outputting the codeblock 'as-is'.

I'll see if I can release a new version via pypi tomorrow.

Thanks for the use-case, never would've thought of that myself ;)

**Comment by hertogp** [comment]
Version 0.1.7 has just been released.
