### ISSUE TITLE
graphvix svg+latex+includegraphics

### ISSUE THREAD

**Issue by jahagirdar** [hertogp/imagine#17]
I have the following code in markdown
```
 ```{.graphviz im_opt="-Gsize=4,1.5" caption="Created by Graphviz"}
  
  digraph {
....
```
This translates to the latex code

```
 \begin{figure}
  \centering
  \includegraphics{pd-images/7ec141f6be6f6a8999be063d7b22457543c418c6.svg}
  \caption{Created by Graphviz}
  \end{figure}
```

It looks like svg files are not supported by includegraphics. Am I missing something here?

**Comment by hertogp** [comment]
When converting to pdf, svg should work as well.  That being said, when I reran my example/graphviz.md through pandoc, the svg images were indeed kinda missing.  Kinda, since the filter did produce svg-files with content in the pd-images subdir. After removing the im_opt="-Gsize=4,1.5" and the size=".." from the example graph, the svg images were visible once more.

So could you try again with (e.g.):
````
```{.graphviz caption="Created by Graphviz"}

digraph finite_state_machine {
  rankdir=LR;
  node [shape = doublecircle]; LR_0 LR_3 LR_4 LR_8;
  node [shape = circle];
  LR_0 -> LR_2 [ label = "SS(B)" ];
  LR_0 -> LR_1 [ label = "SS(S)" ];
  LR_1 -> LR_3 [ label = "S($end)" ];
  LR_2 -> LR_6 [ label = "SS(b)" ];
  LR_2 -> LR_5 [ label = "SS(a)" ];
  LR_2 -> LR_4 [ label = "S(A)" ];
  LR_5 -> LR_7 [ label = "S(b)" ];
  LR_5 -> LR_5 [ label = "S(a)" ];
  LR_6 -> LR_6 [ label = "S(b)" ];
  LR_6 -> LR_5 [ label = "S(a)" ];
  LR_7 -> LR_8 [ label = "S(b)" ];
  LR_7 -> LR_5 [ label = "S(a)" ];
  LR_8 -> LR_6 [ label = "S(b)" ];
  LR_8 -> LR_5 [ label = "S(a)" ];
}
```
````
And convert using `pandoc --filter pandoc-imagine example.md -o example.pdf` and let me know the result?

**Comment by hertogp** [comment]
@jahagirdar 
Any luck with this?
