### ISSUE TITLE
Best way to integrate pandoc-imagine in a Git repository?

### ISSUE THREAD

**Issue by ziotom78** [hertogp/imagine#19]
I am using pandoc-imagine to produce Reveal.js slides for a university curse I am teaching this semester, and it works really great! I put the generated HTML on a GitHub site that is published using GitHub Pages.

I have yet to understand what is the best workflow to integrate pandoc-imagine: every time I re-run my `Makefile`, any image that has been updated gets saved in a file under `pd-images` with a different filename, both for the input (e.g., the Asymptote source code) and the PNG output, which means that I must continually run `git rm` and `git add` to delete the old, unused file and add the new one.

Is there a way to make things simpler? For instance, a way to tell pandoc-imagine to always use the same filename for an imagine instead of generating a new one for each file change?

Many thanks for your program!

**Comment by Synthetica9** [comment]
Why don't you add pd-images to your gitignore?

**Comment by hertogp** [comment]
If I understand correctly, reveal.js uses a single, self-contained html with all its images embedded in the html file. So like @Synthetica9 suggests, you could simply add pd-images/ to your .gitignore and add a "clean" target to `Makefile` that will remove all files in pd-images, which are temporary anyway since the images are being embedded in the slide show's html-file at a later stage.  Once you're happy with a presentation, you run `make clean` to remove the temporary stuff in pd-images/.

**Comment by ziotom78** [comment]
Unfortunately this is not the case with the output produced by Pandoc: images in `pd-images` are referenced within the HTML, not embedded:

    …
    <p><embed width="680px" height="680px" src="pd-images/vector_generators.html" /></p>
    …

(This is exactly the reason why I must keep them in the Git repository, otherwise GitHub Pages would not publish them.)

**Comment by hertogp** [comment]
That kinda depends on how you are generating the reveal presentation.  I use something like:

> pandoc --verbose -s --filter ./lib/pandoc_imagine.py -f markdown+fenced_divs+pipe_tables+escaped_line_breaks+lists_without_preceding_blankline+emoji -t revealjs --template=/home/pdh/dev/prezto/lib/pandoc/reveal.tpl --resource-path=/home/pdh/dev/prezto:/home/pdh/dev/prezto/pd-images:/home/pdh/dev/prezto/slides/demo:/home/pdh/dev/prezto:/home/pdh/dev/prezto/lib:/home/pdh/dev/prezto/lib/reveal  --self-contained --section-divs slides/demo/demo.md -o /home/pdh/dev/prezto/dist/slides/demo/demo-reveal.html

which gives me a self-contained html file with the graphviz image embedded in it (see attached).

Looking at your raytracing_course's Makefile it seems you're not using pandoc's reveal template --template=path/reveal.tpl and are also not including a --resource-path (which tells pandoc where to find reveal libs, images etc..)
[demo-reveal.html.zip](https://github.com/hertogp/imagine/files/6297478/demo-reveal.html.zip)
from 
[demo.md.txt](https://github.com/hertogp/imagine/files/6297481/demo.md.txt)

(had to add .txt to the demo.md in order to include it here)

**Comment by ziotom78** [comment]
Many thanks @hertogp, I tried to add the switch `--self-contained` and it did the trick neatly! (There was no need to patch the template.)

However, as I am incorporating many images and animations, the HTML gets quite huge (~11 MB) and takes some time to compile (30 s instead of 0.2 s). This is not optimal, so I decided to patch my copy of `pandoc-imagine` and make it accept a `im_fname` keyword: if the keyword is specified, it uses that string instead of generating a hexadecimal hash and it overwrites it every time `pandoc` is invoked. This seems to work nicely.

Many thanks for your help and time!
